language: node_js
node_js:
- '0.10'
before_script:
- npm install -g zuul
env:
  global:
    secure: JVRszN2u//7UkoTyHsR9N9iuu+Dy1VsGwaEZo5Jy8oDEQA0gW62wn+l2WbRumVCV0fUQAAjLPzmCygeZe0UE1WeJYguWDHwrZuPriA581fY4gvzrx/AF+y2y1Adg9HXkaCU6tgPB/3LODusycb8z1YVBmwJj51y9MpcE0UOwGX0=
